name: Tagg
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  app_links: ^3.4.5
  dotted_line: ^3.2.3
  file_picker: ^10.3.3
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.2.1
  google_fonts: ^6.3.1
  google_sign_in: ^6.2.0
  http: ^1.5.0
  intl: ^0.20.2
  local_auth: ^2.1.8
  qr_flutter: ^4.1.0
  share_plus: ^7.0.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.0.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_launcher: ^6.3.0
  web_socket_channel: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/svgs/icons/
    - lib/assets/svgs/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/svgs/images/logo.png"
  adaptive_icon_background: "#090715"
  adaptive_icon_foreground: "lib/assets/svgs/images/logo.png"
